# Generated by Django 3.2 on 2022-01-30 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fruits', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fruit',
            name='amount',
            field=models.IntegerField(default=4),
            preserve_default=False,
        ),
    ]
